# Generated by Django 6.0.5 on 2026-05-17 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("login", models.CharField(max_length=50, unique=True)),
                ("mdp_hash", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("agent", "Agent de voyage"),
                            ("receptionniste", "Réceptionniste"),
                            ("comptable", "Comptable"),
                            ("admin", "Administrateur"),
                        ],
                        default="agent",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chambre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=10, unique=True)),
                (
                    "type_chambre",
                    models.CharField(
                        choices=[
                            ("simple", "Simple"),
                            ("double", "Double"),
                            ("suite", "Suite"),
                        ],
                        default="simple",
                        max_length=20,
                    ),
                ),
                ("prix_nuit", models.DecimalField(decimal_places=2, max_digits=15)),
                ("capacite", models.PositiveIntegerField(default=1)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("libre", "Libre"),
                            ("occupee", "Occupée"),
                            ("maintenance", "En maintenance"),
                        ],
                        default="libre",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telephone", models.CharField(max_length=20)),
                ("adresse", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Voyage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("date_depart", models.DateField()),
                ("date_retour", models.DateField()),
                ("prix", models.DecimalField(decimal_places=2, max_digits=15)),
                ("places_dispo", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_reservation", models.DateTimeField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("confirmee", "Confirmée"),
                            ("annulee", "Annulée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "montant_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conakry_travel_hotel.agent",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conakry_travel_hotel.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inclure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_entree", models.DateField()),
                ("date_sortie", models.DateField()),
                (
                    "chambre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conakry_travel_hotel.chambre",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conakry_travel_hotel.reservation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_emission", models.DateTimeField(auto_now_add=True)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "statut_paiement",
                    models.CharField(
                        choices=[
                            ("payee", "Payée"),
                            ("en_attente", "En attente"),
                            ("annulee", "Annulée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "mode_paiement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("especes", "Espèces"),
                            ("orange_money", "Orange Money"),
                            ("mtn_momo", "MTN MoMo"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conakry_travel_hotel.reservation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Concerner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nb_personnes", models.PositiveIntegerField(default=1)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conakry_travel_hotel.reservation",
                    ),
                ),
                (
                    "voyage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conakry_travel_hotel.voyage",
                    ),
                ),
            ],
            options={
                "unique_together": {("reservation", "voyage")},
            },
        ),
    ]
