# Generated by Django 6.0.5 on 2026-05-24 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conakry_travel_hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut_paiement', models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('mode_paiement', models.CharField(blank=True, choices=[('especes', 'Espèces'), ('orange_money', 'Orange Money'), ('mtn_momo', 'MTN MoMo')], max_length=20, null=True)),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facture_obj', to='conakry_travel_hotel.reservation')),
            ],
        ),
    ]
